import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fasha Motors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <nav className="flex items-center justify-between px-4 sm:px-12 md:px-20 border-b border-mainBlue">
          {/* Logo */}
          <div className="flex items-center gap-4">
            <p className="text-mainRed text-[40px] font-semibold">
              F<span className="text-mainBlue text-[25px]">M</span>
            </p>
            <p className="text-mainRed text-[30px] font-semibold">
              Fasha <span className="text-mainBlue">Motors</span>
            </p>
          </div>
          {/* Logout */}
          <button className="cursor-pointer text-sm bg-mainRed text-white px-8 py-2 rounded-full hover:bg-mainRed/80 duration-300 transition-all ease-in-out">
            Logout
          </button>
        </nav>
        {children}
        <footer className="bg-mainBlue text-white px-4 sm:px-12 md:px-20 border-t border-mainRed py-6 sm:py-10 lg:py-12 mt-20">
          {/* Logo */}
          <div className="flex items-center gap-4">
            <p className="text-mainRed text-[40px] font-semibold">
              F<span className="text-white text-[25px]">M</span>
            </p>
            <p className="text-mainRed text-[30px] font-semibold">
              Fasha <span className="text-white">Motors</span>
            </p>
          </div>
          <p className="text-sm tracking-wide max-w-[400px] ">
            Fasha Motors is a one-stop destination for high-quality motorbike
            spare parts and accessories. Whether you’re looking for genuine
            replacements, performance upgrades, or everyday maintenance
            essentials, we provide a wide range of reliable products to keep
            your bike running smoothly.
          </p>
        </footer>
      </body>
    </html>
  );
}
